import { useEffect, useState } from 'react'
import { createMovieList, createSavedMovie, deleteMovieList, deleteSavedMovie, getMovieLists, getSavedMovies, updateMovieList, updateSavedMovie } from './api'
import { getMoviesByIds, getPosterUrl } from '../movie-discovery/tmdbClient'
import './movie-lists.css'

export default function MovieLists({ userId, onSelectList, pendingMovie, onPendingMovieSaved }) {
  const [lists, setLists] = useState([]); const [selectedId, setSelectedId] = useState(''); const [movies, setMovies] = useState([])
  const [metadata, setMetadata] = useState({}); const [newName, setNewName] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const selectedList = lists.find((item) => String(item.id) === String(selectedId))
  async function loadLists(keepId = selectedId) {
    const rows = userId ? await getMovieLists(userId) : []; setLists(rows)
    const nextId = rows.some((item) => String(item.id) === String(keepId)) ? String(keepId) : ''
    setSelectedId(nextId); onSelectList?.(rows.find((item) => String(item.id) === nextId) || null); return nextId
  }
  async function loadMovies(listId = selectedId) { const rows = listId ? await getSavedMovies(listId) : []; setMovies(rows); setMetadata(rows.length ? await getMoviesByIds(rows.map((movie) => movie.tmdbId)) : {}) }
  useEffect(() => { let active = true; Promise.resolve().then(async () => { const listId = await loadLists(''); if (active) await loadMovies(listId) }).catch((cause) => active && setError(cause.message)); return () => { active = false }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId])
  function chooseList(id) { setSelectedId(id); onSelectList?.(lists.find((item) => String(item.id) === String(id)) || null); loadMovies(id).catch((cause) => setError(cause.message)) }
  async function run(action, success) { setBusy(true); setError(''); setMessage(''); try { await action(); setMessage(success) } catch (cause) { setError(cause.message || 'The request could not be completed.') } finally { setBusy(false) } }
  function createList(event) { event.preventDefault(); run(async () => { const created = await createMovieList({ userId, name: newName }); const id = String(created?.data?.id ?? created?.id); if (!id) throw new Error('The API did not return the new list ID.'); setNewName(''); await loadLists(id); await loadMovies(id) }, 'List created and selected.') }
  function renameList() { const name = window.prompt('New list name:', selectedList?.name); if (name === null) return; run(async () => { await updateMovieList(selectedId, { name }); await loadLists(selectedId) }, 'List renamed.') }
  function removeList() { if (!selectedList || !window.confirm('Delete this list and its saved movies?')) return; run(async () => { const failures = []; for (const movie of movies) { try { await deleteSavedMovie(movie.id) } catch { failures.push(movie.id) } } if (failures.length) throw new Error('Could not remove ' + failures.length + ' saved movie(s). The list was kept.'); await deleteMovieList(selectedId); await loadLists(''); setMovies([]); setMetadata({}) }, 'List deleted.') }
  function savePending() { if (!pendingMovie) return; run(async () => { await createSavedMovie({ listId: selectedId, tmdbId: pendingMovie.tmdbId }); await loadMovies(selectedId); onPendingMovieSaved?.() }, 'Movie saved.') }
  function updateMovie(movie, changes) { run(async () => { await updateSavedMovie(movie.id, changes); await loadMovies(selectedId) }, 'Movie details saved.') }
  if (!userId) return <section className="movie-lists"><div className="movie-lists__empty"><h3>Select a profile first</h3><p>Choose or create a user on the Users tab before creating lists.</p></div></section>
  return <section className="movie-lists"><header className="movie-lists__header"><div><p className="movie-lists__eyebrow">YOUR COLLECTION</p><h2>My movies</h2></div><span className="movie-lists__count">{lists.length} lists</span></header>{error && <p className="movie-lists__notice movie-lists__notice--error" role="alert">{error}</p>}{message && <p className="movie-lists__notice movie-lists__notice--success" role="status">{message}</p>}<div className="movie-lists__layout"><aside className="movie-lists__sidebar"><form className="movie-lists__create" onSubmit={createList}><label htmlFor="new-list-name">Create a list</label><div className="movie-lists__input-row"><input id="new-list-name" value={newName} onChange={(event) => setNewName(event.target.value)} required /><button disabled={busy}>+</button></div></form><nav className="movie-lists__nav">{lists.map((list) => <button key={list.id} className={String(list.id) === String(selectedId) ? 'is-active' : ''} onClick={() => chooseList(String(list.id))}>{list.name}<span>›</span></button>)}</nav></aside><div className="movie-lists__content">{selectedList ? <><div className="movie-lists__list-heading"><div><h3>{selectedList.name}</h3><p>{movies.length} saved movies</p></div><div className="movie-lists__actions"><button className="movie-lists__text-button" onClick={renameList}>Rename</button><button className="movie-lists__text-button movie-lists__text-button--danger" onClick={removeList}>Delete list</button></div></div>{pendingMovie && <div className="movie-lists__add-movie"><strong>Save “{pendingMovie.title}” here?</strong><button type="button" onClick={savePending} disabled={busy}>Save to this list</button></div>}<div className="movie-lists__movies">{movies.map((movie) => <MovieCard key={movie.id} movie={movie} details={metadata[String(movie.tmdbId)]} disabled={busy} onSave={updateMovie} onRemove={() => run(async () => { await deleteSavedMovie(movie.id); await loadMovies(selectedId) }, 'Movie removed.')} />)}{!movies.length && <div className="movie-lists__empty"><h4>This list is ready for a movie</h4><p>Save a result from Discover Movies.</p></div>}</div></> : <div className="movie-lists__empty movie-lists__empty--welcome"><h3>Create or select a list</h3><p>Then choose a destination for movies from Discover Movies.</p></div>}</div></div></section>
}
function MovieCard({ movie, details, disabled, onSave, onRemove }) {
  const [rating, setRating] = useState(movie.rating ?? '')
  const title = details?.title || 'TMDB movie ' + movie.tmdbId; const poster = getPosterUrl(details?.poster_path)
  return <article className="movie-lists__movie-card">{poster ? <img className="movie-lists__poster" src={poster} alt={title + ' poster'} /> : <div className="movie-lists__movie-icon">▶</div>}<div className="movie-lists__movie-title"><h4>{title}</h4><span>{details?.release_date?.slice(0, 4) || 'Year unknown'} · TMDB ★ {Number(details?.vote_average || 0).toFixed(1)}</span></div><button className="movie-lists__remove" onClick={() => onRemove(movie)} disabled={disabled}>×</button><div className="movie-lists__movie-fields"><label>Status<select value={movie.status || 'Want to Watch'} onChange={(event) => onSave(movie, { status: event.target.value })} disabled={disabled}><option>Want to Watch</option><option>Watched</option></select></label><label>My rating<input type="number" min="1" max="10" value={rating} onChange={(event) => setRating(event.target.value)} onBlur={() => String(rating) !== String(movie.rating ?? '') && onSave(movie, { rating })} disabled={disabled} /></label></div><p className="movie-lists__hint">Personal notes are unavailable until a notes column is added to savedMovies.</p></article>
}
